#!/usr/bin/env python3
"""Render output/leaderboard.json as a Markdown table."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from leaderboard_common import die, load_json

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_INPUT = REPO_ROOT / "output" / "leaderboard.json"
DEFAULT_OUTPUT = REPO_ROOT / "README.md"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input", type=Path, default=DEFAULT_INPUT, help="Leaderboard JSON path")
    p.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Markdown output path")
    p.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional max number of rows to include (default: all)",
    )
    return p.parse_args()


def fmt_int(value: int | None) -> str:
    if value is None:
        return "—"
    return f"{value:,}"


def fmt_params(value: int | None) -> str:
    if value is None:
        return "—"
    if value >= 1_000_000_000:
        return f"{value / 1_000_000_000:.2f}B"
    if value >= 1_000_000:
        return f"{value / 1_000_000:.1f}M"
    return fmt_int(value)


def fmt_delta(value: int | None) -> str:
    if value is None:
        return "—"
    if value > 0:
        return f"+{value:,}"
    return f"{value:,}"


def escape_cell(text: str | None) -> str:
    if text is None:
        return "—"
    return str(text).replace("|", "\\|").replace("\n", " ")


def hf_org_link(org: str | None) -> str:
    if not org:
        return "—"
    return f"[{escape_cell(org)}](https://huggingface.co/{org})"


def render_markdown(leaderboard: dict, *, limit: int | None = None) -> str:
    rows = list(leaderboard.get("rows") or [])
    if limit is not None:
        rows = rows[:limit]

    lines = [
        "# European LLM Hugging Face download leaderboard",
        "",
        f"- **Snapshot date:** {leaderboard.get('snapshot_date', '—')}",
        f"- **Generated at:** {leaderboard.get('generated_at', '—')}",
        f"- **Ranking metric:** `{leaderboard.get('ranking_metric', 'total_downloads_30d')}` "
        "(last 30 days, summed across official format variants)",
        f"- **Rows:** {len(rows)}"
        + (f" (of {len(leaderboard.get('rows') or [])})" if limit is not None else ""),
        "",
        "| Rank | Model | Country | Developer | Org | Downloads (30d) | Δ 30d | All-time | Params | Repos |",
        "| ---: | --- | :---: | --- | --- | ---: | ---: | ---: | ---: | ---: |",
    ]

    for row in rows:
        incomplete = "" if row.get("complete", True) else " \\*"
        lines.append(
            "| "
            + " | ".join(
                [
                    str(row.get("rank", "")),
                    escape_cell(row.get("display_name")) + incomplete,
                    escape_cell(row.get("country")),
                    escape_cell(row.get("developer")),
                    hf_org_link(row.get("official_org")),
                    fmt_int(row.get("total_downloads_30d")),
                    fmt_delta(row.get("delta_downloads_30d")),
                    fmt_int(row.get("total_downloads_all_time")),
                    fmt_params(row.get("parameters")),
                    str(row.get("repo_count", 0)),
                ]
            )
            + " |"
        )

    if any(not row.get("complete", True) for row in rows):
        lines.extend(
            [
                "",
                "\\* Row marked incomplete: one or more member repos failed during the last fetch.",
            ]
        )

    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- Downloads are Hugging Face Hub **rolling last-30-day** counts, aggregated over official "
            "repos matched by config regexes (GGUF / MLX / FP8 / etc. when published by the same org).",
            "- **Params** is the max reported parameter count among member repos "
            "(`safetensors.total`, else `gguf.total`).",
            "- Machine-readable data: [`output/leaderboard.json`](output/leaderboard.json), "
            "[`output/leaderboard.csv`](output/leaderboard.csv).",
            "- How this is built / how to add models: [`DEVELOPMENT.md`](DEVELOPMENT.md).",
            "- This file is regenerated by CI (`fetch` workflow) via `scripts/render_leaderboard_md.py`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    if not args.input.is_file():
        die(f"Leaderboard JSON not found: {args.input}. Run fetch_download_stats.py first.")
    if args.limit is not None and args.limit < 1:
        die("--limit must be >= 1")

    leaderboard = load_json(args.input)
    markdown = render_markdown(leaderboard, limit=args.limit)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(markdown, encoding="utf-8")
    print(f"Wrote {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
